import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { PostType } from '../types'
import { getAllPosts } from '../util/post'

export async function getStaticProps() {
	const allPosts = getAllPosts()

	return {
		props: {
			allPosts,
		},
	}
}

const Home: NextPage = ({ allPosts }: any) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>next-blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.imagewrapper}>
				<Image
					className={styles.profile}
					width={144}
					height={144}
					priority
					src="/images/blue_profile.png"
					alt="profile"
				/>
			</div>
			<h1 className={styles.title}>blog 📝</h1>
			<div className={styles.bloglists}>
				{allPosts &&
					allPosts.map((data: PostType) => {
						return (
							<Link href={`/${data.id}`} key={data.id}>
								<div className={styles.blog}>{data.id}</div>
							</Link>
						)
					})}
			</div>
		</div>
	)
}

export default Home
