import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { PostType } from '../types'
import { getAllPosts } from '../util/post'

export async function getStaticProps() {
	const allPosts = getAllPosts()

	return {
		props: {
			allPosts,
		},
	}
}

const Home: NextPage = ({ allPosts }: any) => {
	return (
		<div>
			<Head>
				<title>next-blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<Image
					width={144}
					height={144}
					priority
					src="/images/blue_profile.png"
					alt="profile"
				/>
			</div>
			<h1>blog 📝</h1>
			<div>
				{allPosts &&
					allPosts.map((data: PostType) => {
						console.log(data)
						return (
							<Link href={`/${data.id}`} key={data.id}>
								<div>
									<div>{data.data.title}</div>
									<div>
										{data.data.tags.map((tag: string) => (
											<span key={tag}>{tag}</span>
										))}
									</div>
								</div>
							</Link>
						)
					})}
			</div>
		</div>
	)
}

export default Home
