import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { PostType } from '../types'
import { getAllPosts } from '../util/post'

export async function getStaticProps() {
	const allPosts = getAllPosts()

	return {
		props: {
			allPosts,
		},
	}
}

const Home: NextPage = ({ allPosts }: any) => {
	return (
		<div>
			<Head>
				<title>Weekly Digest</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="font-sans __variable_ba7edb">
				<div className=" relative z-10 grid grid-cols-[1fr,min(640px,100%),1fr] gap-y-8 px-4 pt-48 font-sans text-base  xl:grid-cols-[1fr,minmax(auto,240px),min(640px,100%),minmax(auto,240px),1fr] xl:gap-x-9 xl:px-0 [&>*]:col-start-2 xl:[&>*]:col-start-3">
					{allPosts &&
						allPosts.map((data: PostType) => {
							const { id, data: singleData } = data
							return (
								<div
									key={id}
									className="hover:cursor-pointer block overflow-hidden rounded-2xl bg-white/5 p-7 shadow-surface-elevation-low transition duration-300 hover:bg-white/10 hover:shadow-surface-elevation-medium focus:outline-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-500/70"
								>
									<Link href={`/${id}`}>
										<div>
											<div className="flex justify-between">
												<div className="text-xl  transition duration-300 line-clamp-2">
													{singleData.title}
												</div>

												<div className=" text-gray-500">{singleData.date}</div>
											</div>

											<div className="mt-4 text-lg line-clamp-3">
												{singleData.description}
											</div>
											<div className="flex flex-wrap space-x-2 text-base mt-2">
												{singleData.tags.map((tag: string) => (
													<div
														className=" rounded-md shadow-surface-elevation-low bg-white/10 px-2 
													"
														key={tag}
													>
														{tag}
													</div>
												))}
											</div>
										</div>
									</Link>
								</div>
							)
						})}
				</div>
			</main>
		</div>
	)
}

export default Home
